ALTER TABLE Tickets
    ADD COLUMN customer_id INTEGER,
    ADD CONSTRAINT fk_customers FOREIGN KEY (customer_id) REFERENCES Customers(id) ON DELETE CASCADE;

ALTER TABLE Tickets
    ADD COLUMN event_id INTEGER,
    ADD CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE;

ALTER TABLE Customers
    ADD COLUMN user_id INTEGER,
    ADD CONSTRAINT fk_user_customers FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE;

ALTER TABLE Admins
    ADD COLUMN user_id INTEGER,
    ADD CONSTRAINT fk_user_admins FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE;

ALTER TABLE Users
    ADD COLUMN role_id INTEGER,
    ADD CONSTRAINT fk_role_users FOREIGN KEY (role_id) REFERENCES User_Roles(id) ON DELETE CASCADE;



ALTER TABLE Events
    ADD COLUMN place_id INTEGER,
    ADD CONSTRAINT fk_place FOREIGN KEY (place_id) REFERENCES Places(id) ON DELETE CASCADE;